# Generated by Django 4.1.7 on 2023-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('HouseholdID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
