# Generated by Django 4.1.7 on 2023-03-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_islandapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('ApplianceID', models.AutoField(primary_key=True, serialize=False)),
                ('ApplianceName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceTypes',
            fields=[
                ('ApplianceTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('ApplianceTypeName', models.CharField(max_length=100, null=True)),
                ('EnergyConsumptionRate', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyRates',
            fields=[
                ('RateID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDatetime', models.DateTimeField(null=True)),
                ('EndDatetime', models.DateTimeField(null=True)),
                ('EnergyRate', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='households',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='households',
            name='NumOccupants',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='households',
            name='NumRooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='households',
            name='TotalSqFt',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('EnergyUsageID', models.AutoField(primary_key=True, serialize=False)),
                ('UsageDatetime', models.DateTimeField(null=True)),
                ('EnergyConsumed', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ApplianceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_islandapp.appliances')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('BillingID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDateime', models.DateTimeField(null=True)),
                ('EndDatetime', models.DateTimeField(null=True)),
                ('TotalEnergyConsumed', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('TotalCost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('EnergyRateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_islandapp.energyrates')),
                ('HouseholdID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_islandapp.households')),
            ],
        ),
        migrations.AddField(
            model_name='appliances',
            name='ApplianceTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_islandapp.appliancetypes'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='HouseholdID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_islandapp.households'),
        ),
    ]
